# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: code2config

on:
  push:
    branches: [ master ]
    paths: 
      - .distribute/groups.yml
      - .distribute/releases.yml

jobs:
  sync-groups:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v1.2.0
    
    - name: Install dependencies
      run: |
        pip install PyYAML
        pip install requests
    
    - name: Run Script
      run: |
        python .github/workflows/lib/put_groups.py $GITHUB_REPOSITORY ${{secrets.APP_CENTER_TOKEN}}
        python .github/workflows/lib/put_releases.py $GITHUB_REPOSITORY ${{secrets.APP_CENTER_TOKEN}}
        python .github/workflows/lib/get_groups.py $GITHUB_REPOSITORY ${{secrets.APP_CENTER_TOKEN}}
        python .github/workflows/lib/get_releases.py $GITHUB_REPOSITORY ${{secrets.APP_CENTER_TOKEN}}
        git config --global user.email "ahdbilal@github.com"
        git config --global user.name "ahdbilal"
        git add .distribute/groups.yml
        git add .distribute/releases.yml
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "updated groups/releases"
          remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git push "${remote_repo}" HEAD:master --force
        else
          echo "no changes";
        fi
        
